# Generated by Django 5.1.2 on 2024-10-27 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-mod_date',), 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
        migrations.RemoveField(
            model_name='board',
            name='date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='text',
        ),
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(default='', verbose_name='CONTENT'),
        ),
        migrations.AddField(
            model_name='board',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
        migrations.AddField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='PUBLISH DATE'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100, verbose_name='TITLE'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='blogs_Boards',
        ),
    ]
