# Generated by Django 5.1.2 on 2024-10-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_board_options_remove_board_author_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='blog_Boards',
        ),
    ]
