# Generated by Django 5.1.2 on 2024-10-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_board_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='HITS'),
        ),
    ]
