# Generated by Django 5.1.2 on 2024-10-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_board_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
