# Generated by Django 5.1.2 on 2024-10-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_board_enable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-id',), 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
    ]
