# Generated by Django 5.1.2 on 2024-10-31 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='TITLE')),
                ('content', models.TextField(default='', verbose_name='CONTENT')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='HITS')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='PUBLISH DATE')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
                ('enable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'db_table': 'board_Boards',
                'ordering': ('-id',),
            },
        ),
    ]
